title: Jordon Smith
description: Personal website of Jordon Smith
url: http://jordonsmith.uk
signoff: Jordon Smith
disqus_shortname: jordonsmith
google_analytics: UA-58207281-1
links:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Email
    url: mailto:jordon@jordonsmith.uk
    external: true
  - name: GitHub
    url: https://github.com/jrdnull
    external: true
highlighter: pygments
permalink: pretty
markdown: redcarpet
redcarpet:
  extensions:
    - smart
